<?php ?><!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administración de turnos | IFER</title>
<style>body{font:16px system-ui,sans-serif;background:#f4f7f8;color:#164c5b;margin:0}main{max-width:1000px;margin:40px auto;padding:24px}section{background:#fff;padding:24px;margin:18px 0;box-shadow:0 8px 24px #164c5b18}input,select,button{padding:10px;margin:5px;border:1px solid #ccd9dc}button{background:#2c9a9a;color:#fff;border:0;cursor:pointer}.hidden{display:none}.message{margin:12px 0}</style></head>
<body><main><h1>Agenda IFER</h1><section id="login"><h2>Ingresar</h2><form id="loginForm"><input name="username" placeholder="Usuario" autocomplete="username" required><input type="password" name="password" placeholder="Contraseña" autocomplete="current-password" required><button>Ingresar</button></form></section>
<div id="panel" class="hidden"><p class="message" id="message"></p><p id="currentUser"></p><button id="logout">Cerrar sesión</button><section><h2>Especialidades</h2><form data-action="save-specialty"><input name="name" placeholder="Nueva especialidad" required><button>Guardar</button></form><ul id="specialties"></ul></section>
<section><h2>Médicos</h2><form data-action="save-doctor"><input name="id" placeholder="Identificador, ej. garcia" required><input name="name" placeholder="Nombre del médico" required><select name="specialty_id" id="specialtySelect" required></select><button>Guardar</button></form><ul id="doctors"></ul></section>
<section><h2>Horarios</h2><form data-action="save-schedule"><select name="doctor_id" id="doctorSelect" required></select><select name="weekday"><option value="1">Lunes</option><option value="2">Martes</option><option value="3">Miércoles</option><option value="4">Jueves</option><option value="5">Viernes</option><option value="6">Sábado</option></select><input type="time" name="start_time" value="08:00" required><input type="time" name="end_time" value="18:00" required><input type="number" name="slot_minutes" value="30" min="5" step="5"><button>Guardar horario</button></form><ul id="schedules"></ul></section>
<section id="usersSection" class="hidden"><h2>Usuarios del panel</h2><form data-action="save-user"><input name="username" placeholder="Usuario" required><input name="display_name" placeholder="Nombre completo" required><input type="password" name="password" placeholder="Contraseña, mínimo 10 caracteres" minlength="10" required><select name="role"><option value="operator">Operador</option><option value="admin">Administrador</option></select><button>Guardar usuario</button></form><ul id="users"></ul></section></div></main>
<script>
const api='api.php', login=document.getElementById('login'), panel=document.getElementById('panel'), message=document.getElementById('message');
async function request(action, options={}){const response=await fetch(`${api}?action=${action}`,options);return response.json()}
function show(text){message.textContent=text}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g, character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]))}
async function load(){const result=await request('data');if(!result.ok){login.classList.remove('hidden');panel.classList.add('hidden');return}login.classList.add('hidden');panel.classList.remove('hidden');document.getElementById('currentUser').textContent=`Sesión: ${result.current_user.display_name} (${result.current_user.role})`;document.getElementById('specialties').innerHTML=result.specialties.map(item=>`<li>${escapeHtml(item.name)}</li>`).join('');document.getElementById('doctors').innerHTML=result.doctors.map(item=>`<li>${escapeHtml(item.name)}</li>`).join('');document.getElementById('specialtySelect').innerHTML=result.specialties.map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('');document.getElementById('doctorSelect').innerHTML=result.doctors.map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('');document.getElementById('schedules').innerHTML=result.schedules.map(item=>`<li>${escapeHtml(item.doctor_id)}: día ${item.weekday}, ${item.start_time} a ${item.end_time}, cada ${item.slot_minutes} min</li>`).join('');const usersSection=document.getElementById('usersSection');usersSection.classList.toggle('hidden',result.current_user.role!=='admin');document.getElementById('users').innerHTML=(result.users||[]).map(item=>`<li>${escapeHtml(item.display_name)} (${escapeHtml(item.username)}, ${item.role}) - ${item.active ? 'Activo' : 'Inactivo'} <button type="button" data-user-id="${item.id}">${item.active ? 'Desactivar' : 'Activar'}</button></li>`).join('');document.querySelectorAll('[data-user-id]').forEach(button=>button.addEventListener('click',async()=>{const body=new FormData();body.append('id',button.dataset.userId);const response=await request('toggle-user',{method:'POST',body});show(response.message);if(response.ok)load()}))}
document.getElementById('loginForm').addEventListener('submit',async event=>{event.preventDefault();const result=await request('login',{method:'POST',body:new FormData(event.target)});show(result.message);if(result.ok)load()});document.querySelectorAll('form[data-action]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const result=await request(form.dataset.action,{method:'POST',body:new FormData(form)});show(result.message);if(result.ok){form.reset();load()}}));document.getElementById('logout').addEventListener('click',async()=>{await request('logout');load()});load();
</script></body></html>
